export const BADGES = [
  { slug: 'started', name: 'Started', rarity: 'common', meaning: 'Took the first step with Sisi', description: 'Finish onboarding.' },
  { slug: 'budget-builder', name: 'Budget Builder', rarity: 'common', meaning: 'Built my first budget', description: 'Complete the First budget milestone.' },
  { slug: 'savings-streak', name: 'Savings Streak', rarity: 'rare', meaning: 'Took action in 4 different weeks', description: 'Complete actions in 4 different weeks.' },
  { slug: 'investor-ready', name: 'Investor Ready', rarity: 'rare', meaning: 'Took my first step into investing', description: 'Finish Invest HER.' },
  { slug: 'wealth-builder', name: 'Wealth Builder', rarity: 'epic', meaning: 'Completed all 5 money milestones', description: 'Complete all five milestones.' },
  { slug: 'first-lesson', name: 'First Lesson', rarity: 'common', meaning: 'Finished my first lesson', description: 'Complete 1 lesson.' },
  { slug: 'quiz-whiz', name: 'Quiz Whiz', rarity: 'rare', meaning: 'Aced 5 quizzes', description: 'Get 5 perfect quizzes.' },
  { slug: 'curious-mind', name: 'Curious Mind', rarity: 'rare', meaning: 'Finished 10 lessons', description: 'Complete 10 lessons.' },
  { slug: 'glow-3w', name: '3-Week Glow', rarity: 'common', meaning: 'Hit my weekly target 3 weeks running', description: 'Hit your weekly target 3 weeks in a row.' },
  { slug: 'bloom-12w', name: '12-Week Bloom', rarity: 'epic', meaning: 'Hit my weekly target 12 weeks running', description: 'Hit your weekly target 12 weeks in a row.' },
  { slug: 'circle-starter', name: 'Circle Starter', rarity: 'common', meaning: 'Joined my first Circle session', description: 'Attend your first session.' },
  { slug: 'show-up-sisi', name: 'Show-Up Sisi', rarity: 'rare', meaning: 'Showed up to 4 Circle sessions', description: 'Attend 4 sessions.' },
  { slug: 'workshop-goer', name: 'Workshop Goer', rarity: 'common', meaning: 'Checked in to my first workshop', description: 'Check in to your first event.' },
  { slug: 'circle-cup-champion', name: 'Circle Cup Champion', rarity: 'epic', meaning: 'My Circle won the monthly Circle Cup', description: 'Be in the winning Circle for the month.' },
  { slug: 'better-together', name: 'Better Together', rarity: 'rare', meaning: 'Hit a milestone with my Money Buddy', description: 'Complete a joint buddy milestone.' },
  { slug: 'hype-girl', name: 'Hype Girl', rarity: 'rare', meaning: 'Brought a friend to Sisi', description: 'A friend joins through your link.' },
  { slug: 'oweek-starter', name: 'O-Week Starter', rarity: 'common', meaning: 'Finished the O-Week Starter course', description: 'Finish the O-Week mini-course.' },
  { slug: 'founding-member', name: 'Founding Member', rarity: 'epic', meaning: 'Joined Sisi during the beta', description: 'Join during the beta.' },
  { slug: 'campus-cup-champion', name: 'Campus Cup Champion', rarity: 'epic', meaning: 'My community won the Campus Cup', description: 'Be in the winning community of a Campus Cup season.' },
  { slug: 'payslip-pro', name: 'Payslip Pro', rarity: 'common', meaning: 'Decoded my first payslip', description: 'Finish the First Payslip simulator.' },
  { slug: 'goal-getter', name: 'Goal Getter', rarity: 'rare', meaning: 'Reached a savings goal', description: 'Reach one of your savings goals.' },
  { slug: 'plain-talker', name: 'Word Wise', rarity: 'common', meaning: 'Learned 10 money terms', description: 'Look up 10 glossary terms.' },
] as const;
