/* Mock content for the Community area. Everything here is placeholder copy to be replaced by the team's drafts. */

export type CommunitySeed = { slug: string; name: string; kind: 'university' | 'workplace' | 'community'; emoji: string; color: string; description: string; tags: string[]; joinCode: string; requiresApproval?: boolean };

export const COMMUNITY_SEEDS: CommunitySeed[] = [
  { slug: 'wits', name: 'Wits University', kind: 'university', emoji: '🎓', color: '#D81B60', description: 'Wits women building money confidence together: allowances, NSFAS, first jobs and everything between.', tags: ['campus', 'NSFAS', 'budgeting', 'first-year'], joinCode: 'WITS26' },
  { slug: 'uj', name: 'University of Johannesburg', kind: 'university', emoji: '🏛️', color: '#7E57C2', description: 'UJ sisters swapping saving tips and keeping each other on track.', tags: ['campus', 'saving', 'student-life'], joinCode: 'UJ26' },
  { slug: 'pps-yp', name: 'PPS Young Professionals', kind: 'workplace', emoji: '💼', color: '#0F7B5F', description: 'First-jobbers making sense of payslips, tax and the first big decisions. Approval needed to keep it focused.', tags: ['first-salary', 'payslip', 'investing', 'career'], joinCode: 'PPSYP26', requiresApproval: true },
  { slug: 'first-salary-club', name: 'First Salary Club', kind: 'community', emoji: '💸', color: '#D81B60', description: 'Just got your first salary? Start here. Payslips, budgets and not blowing it all in week one.', tags: ['first-salary', 'payslip', 'budgeting'], joinCode: 'FIRST26' },
  { slug: 'student-savers', name: 'Student Savers', kind: 'community', emoji: '🪙', color: '#F2B33D', description: 'Make an allowance or NSFAS money last the whole month. Tiny habits, real results.', tags: ['NSFAS', 'allowance', 'saving', 'student-life'], joinCode: 'SAVE26' },
  { slug: 'invest-curious', name: 'Invest Curious', kind: 'community', emoji: '🌱', color: '#0F7B5F', description: 'For women who want to start investing small. TFSAs, unit trusts and no jargon.', tags: ['investing', 'TFSA', 'unit-trusts', 'small-amounts'], joinCode: 'INVEST26' },
  { slug: 'side-hustle-sisters', name: 'Side Hustle Sisters', kind: 'community', emoji: '🧵', color: '#AD1457', description: 'Earning on the side? Talk pricing, invoices, tax and keeping what you earn.', tags: ['side-hustle', 'income', 'tax', 'entrepreneurs'], joinCode: 'HUSTLE26' },
  { slug: 'stokvel-sisters', name: 'Stokvel Sisters', kind: 'community', emoji: '🤝', color: '#F2B33D', description: 'How groups save together. Stokvel basics, rules that work and avoiding the drama.', tags: ['stokvel', 'saving', 'groceries', 'community'], joinCode: 'STOKVEL26' },
  { slug: 'family-and-money', name: 'Family & Money', kind: 'community', emoji: '🏠', color: '#7E57C2', description: 'Supporting family and still looking after yourself. Boundaries without guilt.', tags: ['black-tax', 'family', 'boundaries', 'budgeting'], joinCode: 'FAMILY26' },
  { slug: 'debt-free-starters', name: 'Debt-Free Starters', kind: 'community', emoji: '🧾', color: '#E5484D', description: 'Store cards, credit scores and getting out from under. A judgement-free zone. Approval needed.', tags: ['debt', 'credit', 'store-cards'], joinCode: 'DEBT26', requiresApproval: true },
  { slug: 'cape-town-sisters', name: 'Cape Town Sisters', kind: 'community', emoji: '🌊', color: '#0F7B5F', description: 'Cape Town women meeting up (online and in person) to talk money.', tags: ['Cape Town', 'meetups', 'local'], joinCode: 'CPT26' },
  { slug: 'rent-and-independence', name: 'Rent & Independence', kind: 'community', emoji: '🔑', color: '#D81B60', description: 'Moving out? Splitting rent, deposits and surviving the first flat budget.', tags: ['rent', 'moving-out', 'first-flat', 'budgeting'], joinCode: 'RENT26' },
];

export type CircleSeed = { community: string; name: string; topic: string; weekday: number; start: string };
export const CIRCLE_SEEDS: CircleSeed[] = [
  { community: 'wits', name: 'First Salary Sisters', topic: 'Making your first salary work', weekday: 2, start: '18:00' },
  { community: 'wits', name: 'TFSA Thursdays', topic: 'Tax-free savings, step by step', weekday: 4, start: '17:30' },
  { community: 'wits', name: 'Budget Besties', topic: 'Budgets that survive the month', weekday: 3, start: '18:30' },
  { community: 'wits', name: 'Invest Curious Wits', topic: 'Small-amount investing, explained', weekday: 1, start: '17:00' },
  { community: 'uj', name: 'UJ Money Moves', topic: 'Student budgets and saving', weekday: 3, start: '17:00' },
  { community: 'uj', name: 'UJ Side Hustlers', topic: 'Earning more, keeping more', weekday: 5, start: '16:00' },
  { community: 'pps-yp', name: 'Early Career Circle', topic: 'From payslip to plan', weekday: 2, start: '18:00' },
  { community: 'first-salary-club', name: 'Payslip Decoders', topic: 'Reading your pay and planning around it', weekday: 1, start: '18:30' },
  { community: 'student-savers', name: 'Allowance Avengers', topic: 'Stretching an allowance', weekday: 4, start: '17:00' },
  { community: 'invest-curious', name: 'R200 a Month', topic: 'Investing with small amounts', weekday: 3, start: '19:00' },
  { community: 'side-hustle-sisters', name: 'Invoice Club', topic: 'Pricing, invoicing and tax basics', weekday: 2, start: '19:00' },
  { community: 'stokvel-sisters', name: 'Stokvel Starters', topic: 'Starting and running a stokvel', weekday: 6, start: '10:00' },
  { community: 'family-and-money', name: 'Boundaries & Budgets', topic: 'Supporting family without burning out', weekday: 0, start: '17:00' },
  { community: 'debt-free-starters', name: 'Clear the Cards', topic: 'Paying off store cards, step by step', weekday: 3, start: '19:30' },
  { community: 'cape-town-sisters', name: 'Mother City Money', topic: 'Local meetups and budgeting', weekday: 6, start: '11:00' },
  { community: 'rent-and-independence', name: 'First Flat Fund', topic: 'Deposits, rent and a flat budget', weekday: 4, start: '18:00' },
];

export type EventSeed = { slug: string; community: string | null; type: 'workshop' | 'expert_qa' | 'oweek' | 'meetup'; title: string; description: string; agenda: string[]; hostName: string; hostRole: string; dayOffset: number; hour: number; minutes: number; location: string; online: boolean; capacity: number; booked: number; waitlisted?: number; emoji: string };
export const EVENT_SEEDS: EventSeed[] = [
  { slug: 'o-week-r500', community: 'wits', type: 'oweek', title: 'O-Week Starter: your first R500 plan', description: 'A friendly welcome to Sisi for new students. Build a tiny plan for your first month, meet your Circle and win your first badge.', agenda: ['Welcome and what Sisi is (10 min)', 'Build a R500 first-month plan (20 min)', 'Meet your Circle (15 min)', 'Q&A (15 min)'], hostName: 'Thandi Mokoena', hostRole: 'Circle facilitator', dayOffset: 2, hour: 17, minutes: 60, location: 'Great Hall, Wits (venue placeholder)', online: false, capacity: 60, booked: 38, emoji: '🎒' },
  { slug: 'first-payslip', community: 'pps-yp', type: 'workshop', title: 'Your first payslip, decoded', description: 'Gross, net, PAYE and UIF without the headache. Bring your payslip (or a sample) and leave knowing what every line means.', agenda: ['Gross vs net (10 min)', 'What comes off and why (15 min)', 'Spot a payslip mistake (10 min)', 'Questions (10 min)'], hostName: 'Naledi Nkosi', hostRole: 'PPS associate (placeholder)', dayOffset: 3, hour: 18, minutes: 55, location: 'Online (link sent after booking)', online: true, capacity: 40, booked: 28, emoji: '🧾' },
  { slug: 'emergency-fund-student', community: 'wits', type: 'workshop', title: 'Building an emergency fund on a student budget', description: 'Start with R500. Learn where to keep it, how to protect it and how to build it on an allowance.', agenda: ['Why R500 first (10 min)', 'Where to keep it (10 min)', 'Your 4-week plan (20 min)'], hostName: 'Lerato Sithole', hostRole: 'Peer facilitator', dayOffset: 5, hour: 17, minutes: 50, location: 'Online (link sent after booking)', online: true, capacity: 30, booked: 22, emoji: '🛟' },
  { slug: 'stokvel-saturday', community: 'stokvel-sisters', type: 'workshop', title: 'Stokvel Saturday: how groups save together', description: 'Rotating, grocery and burial stokvels: how they work, the rules that keep them fair, and the red flags.', agenda: ['Types of stokvel (15 min)', 'Rules that work (20 min)', 'Starting your own (15 min)'], hostName: 'Busi Radebe', hostRole: 'Community host', dayOffset: 6, hour: 10, minutes: 60, location: 'Online (link sent after booking)', online: true, capacity: 25, booked: 14, emoji: '🤝' },
  { slug: 'ask-a-pro-r200', community: null, type: 'expert_qa', title: 'Ask a professional: investing with R200 a month', description: 'A PPS-approved professional answers your beginner investing questions. General education, not personalised advice. Nearly full: book early.', agenda: ['Short intro (5 min)', 'Your questions, answered (35 min)', 'Next steps (10 min)'], hostName: 'Zanele Khumalo', hostRole: 'PPS-approved professional (placeholder)', dayOffset: 8, hour: 18, minutes: 50, location: 'Online (link sent after booking)', online: true, capacity: 12, booked: 11, emoji: '🙋' },
  { slug: 'cape-town-coffee', community: 'cape-town-sisters', type: 'meetup', title: 'Cape Town Sisters: coffee and budgets', description: 'Informal meetup. Bring a question, a budget or just yourself.', agenda: ['Arrivals and coffee', 'Table chats by topic', 'Swap one tip each'], hostName: 'Amahle Cele', hostRole: 'Community host', dayOffset: 9, hour: 10, minutes: 90, location: 'Cape Town CBD café (to be confirmed)', online: false, capacity: 15, booked: 9, emoji: '☕' },
  { slug: 'side-hustle-tax', community: 'side-hustle-sisters', type: 'workshop', title: 'Side hustle money: invoices and tax basics', description: 'How to price, invoice and think about tax on side income. Check current SARS rules for your situation.', agenda: ['Pricing without undercharging (15 min)', 'A simple invoice (15 min)', 'Tax basics (20 min)'], hostName: 'Priya Naidoo', hostRole: 'Community host', dayOffset: 10, hour: 19, minutes: 50, location: 'Online (link sent after booking)', online: true, capacity: 20, booked: 12, emoji: '🧵' },
  { slug: 'debt-basics', community: 'debt-free-starters', type: 'workshop', title: 'Debt-free basics: store cards and credit scores', description: 'How store cards really cost you, what a credit score is and a first plan to clear what you owe. Full: join the waitlist.', agenda: ['The real cost of a store card (15 min)', 'Credit score basics (15 min)', 'A first payoff plan (20 min)'], hostName: 'Aisha Patel', hostRole: 'Peer facilitator', dayOffset: 12, hour: 19, minutes: 50, location: 'Online (link sent after booking)', online: true, capacity: 10, booked: 10, waitlisted: 3, emoji: '🧾' },
  { slug: 'rent-first-flat', community: 'rent-and-independence', type: 'workshop', title: 'Your first flat: the real monthly cost', description: 'Rent is only the start. Deposit, utilities, transport and the surprise costs, with a worked example.', agenda: ['The full cost list (15 min)', 'Splitting costs fairly (15 min)', 'Build a flat budget (20 min)'], hostName: 'Ayanda Zulu', hostRole: 'Peer facilitator', dayOffset: 14, hour: 18, minutes: 50, location: 'Online (link sent after booking)', online: true, capacity: 25, booked: 8, emoji: '🔑' },
  { slug: 'tfsa-explained-past', community: 'invest-curious', type: 'workshop', title: 'TFSAs explained (replay available soon)', description: 'What a tax-free savings account is and how to choose one. This event has finished.', agenda: ['What is a TFSA', 'Limits and penalties', 'Choosing a provider'], hostName: 'Kea Mahlangu', hostRole: 'Community host', dayOffset: -6, hour: 18, minutes: 50, location: 'Online', online: true, capacity: 30, booked: 24, emoji: '🌱' },
  { slug: 'budget-bootcamp-past', community: 'uj', type: 'workshop', title: 'Budget bootcamp', description: 'A hands-on 50/30/20 workshop. This event has finished.', agenda: ['50/30/20', 'Build yours', 'Share one win'], hostName: 'Palesa Molefe', hostRole: 'Peer facilitator', dayOffset: -14, hour: 17, minutes: 60, location: 'UJ Library seminar room (placeholder)', online: false, capacity: 40, booked: 33, emoji: '📊' },
];

export const ANNOUNCEMENTS: Record<string, string[]> = {
  default: ['Welcome! Be kind, keep it private, and never share account numbers, ID numbers or exact amounts.', 'New this week: check the Events tab for workshops you can book in two taps.'],
  wits: ['O-Week Starter is open for booking. Bring a friend!'],
  'pps-yp': ['Payslip workshop this week. Bring a sample payslip (hide your ID number).'],
  'debt-free-starters': ['This is a judgement-free space. If money stress feels heavy, the Support page has free counselling lines.'],
};

export const CHALLENGE_SEEDS = [
  { title: 'Track every rand for 3 days', description: 'Note down what you spend for three days. No judgement, just noticing.', points: 20 },
  { title: 'Name your savings goal', description: 'Pick one thing you are saving for and tell your Circle what it is (not the amount!).', points: 20 },
];

export const MEMBER_NAMES = [
  'Lerato Sithole', 'Zanele Khumalo', 'Aisha Patel', 'Palesa Molefe', 'Naledi Nkosi', 'Ayanda Zulu', 'Kea Mahlangu', 'Lindiwe Ndlovu', 'Refilwe Mabaso', 'Busi Radebe',
  'Chloe van der Merwe', 'Priya Naidoo', 'Amahle Cele', 'Tumi Moloi', 'Karabo Tau', 'Fatima Essop', 'Nandi Shabalala', 'Rethabile Pule', 'Ntombi Dube', 'Megan Jacobs',
  'Yolanda Gumede', 'Boitumelo Sebola', 'Anele Mkhize', 'Siya Kunene', 'Thabi Mokgosi', 'Zinhle Buthelezi', 'Jade Pillay', 'Mpho Letsoalo', 'Onalenna Seane', 'Lwazi Ngcobo',
  'Candice Botha', 'Dineo Mahlaba', 'Ncediwe Xaba', 'Shanice Adams', 'Kgomotso Phiri', 'Aphiwe Dlamini', 'Reabetswe Motaung', 'Nosipho Zondi', 'Hlengiwe Cele', 'Tshepiso Maseko',
];

/** Circle/community chat lines by topic. Friendly and general; never financial advice. */
export const CHAT_POOLS: Record<string, string[]> = {
  general: ['Hey everyone! Happy to be here 💗', 'Anyone else trying the weekly challenge?', 'Small steps, right? Day two of tracking done', 'Thank you all for being so kind here, it makes this less scary', 'See you at the next session!', 'Proud of us honestly. A month ago I never opened my banking app', 'Quick question: how do you all remember to do your 3 minutes?', 'I set a reminder for after supper and it actually works', 'That lesson was shorter than I expected, love that', 'Does anyone else get a little thrill from checking off the weekly action?', 'I told my flatmate about Sisi and now she wants in 😄', 'Rough week but I still did my 3 minutes, small win', 'What was everyone’s favourite lesson so far?', 'The quiz retries are a gift, I needed three goes 😅', 'Morning sisis ☀️ who is doing their lesson before class?', 'Reminder to drink water and check your budget, in that order 💧', 'I love that nobody here makes me feel silly for asking basic questions', 'Shoutout to whoever suggested the topic about first tax returns, yes please!'],
  budget: ['I tried the 50/30/20 split and rent alone is more than 50% 😅', 'That is okay, adjust it to fit your life. A plan beats perfection', 'Found two subscriptions I forgot about, cancelled both', 'Reading last month’s statement was scary but useful', 'Wants are allowed to exist, they just come second 😂', 'Anyone have a budget template they like?', 'The builder in Milestones took me five minutes', 'My biggest leak is food delivery, I counted it up and wow', 'I split my budget into weekly chunks and it feels so much more doable', 'Tip: round every expense up, it gives you breathing room', 'Does airtime count under needs or wants? Asking for a friend 😅', 'I paid myself first this month and did not even miss it', 'Seeing wants at 30% made me feel less guilty about my coffee', 'Month-end me thanks start-of-month me for planning'],
  savings: ['Emergency fund target: R500 first, nobody judge me', 'No judgement here, R500 is a great start 💗', 'I set up a small transfer for the day after payday', 'Pay yourself first, spend what is left. It works!', 'Separate account made a huge difference for me', 'R100 a month is R1,200 in a year, I did the maths', 'I opened a separate pocket just for emergencies and named it ‘Not for shopping’ 😂', 'R50 a week adds up, my first R200 felt huge', 'Automation is the real hero, I forget it exists and it grows', 'Saving for a laptop, tiny steps but the progress ring motivates me', 'I moved my savings out of sight and it stopped disappearing'],
  invest: ['Does anyone know where to check the TFSA limits? I keep forgetting', 'SARS website, they update it. The lesson said to always check current numbers', 'The fees lesson was an eye opener', 'Ask for the total yearly fee in writing, that was the tip', 'Compound growth chart in the simulator is so satisfying', 'Reminder that illustrations are not forecasts 🙂', 'Tried the simulator with different years, patience really is the superpower', 'I like that it is clearly labelled a simulation, no pressure', 'Still learning what a unit trust actually holds, anyone explain like I am five?', 'A fund is a basket of many companies, so one bad apple does not sink you', 'Checked the fee on my provider’s page, it was in the small print'],
  payslip: ['UIF is a small deduction that funds unemployment cover, I had no idea', 'Gross is not what you get paid, mind blown 😅', 'Net pay is the number to budget with', 'Check every deduction before you panic', 'My first payslip looked like a puzzle, the workshop helped', 'Found my UIF line, it is small but it is there 🙌', 'HR explained my deductions in two minutes after I asked politely', 'I compared my payslip to the sample one, mine looks almost the same', 'Pay date is the 25th so I plan around it now'],
  student: ['NSFAS allowance has to stretch the whole period, planning it by week helped', 'Data bundles are my biggest leak 🙈', 'Cooking in bulk on Sundays saved me so much', 'Protect one thing you love, trim the rest', 'Meal prepping on Sundays is saving me so much this month', 'Does anyone have tips for stretching an allowance over a long month?', 'I track data usage now, turns out streaming is the culprit', 'Library study sessions are free entertainment 😂'],
  stokvel: ['Our grocery stokvel pays out in December, such a good forced saving', 'Write down the rules before the first contribution, it avoids drama', 'Rotating stokvels depend on everyone paying on time, trust matters', 'We take proof of payment for every contribution', 'Our rule: contributions are due on the 1st, no exceptions, and it works', 'We rotate who hosts the payout meeting, keeps it fun', 'A written constitution saved our stokvel from a big fight'],
  family: ['Supporting family is real money, it belongs in the budget', 'I agreed on a monthly amount instead of random asks, it helped', 'Boundaries are not selfish 💗', 'Tell them what you can do, not just what you cannot', 'I set a monthly ‘family fund’ amount and it removed the guilt', 'Saying no kindly is a skill, I am practising 😅', 'I told my mom what I can give each month and she understood better than I expected'],
  debt: ['Store cards: a 10% discount can cost far more in interest', 'Paying more than the minimum made the difference', 'Checking my credit report was less scary than I thought', 'One card at a time, start with the highest interest', 'Paid off my smallest store card first, the momentum felt amazing', 'I called to ask about my interest rate, it was a scary five minutes but worth it', 'No new store cards this month, small win'],
  hustle: ['I finally wrote my first invoice, it looked so professional', 'Price for your time, not just your materials', 'Keep business and personal money separate if you can', 'Side income may be taxable, check current SARS rules', 'Raised my prices by 10% and nobody complained 🙌', 'I use a simple spreadsheet to track what I earn and what I spend on materials', 'Invoices on time means paid on time, it is wild'],
  rent: ['Do not forget the deposit, utilities and transport in the flat budget', 'We split electricity by usage, fewer arguments', 'Keep proof of every rent payment', 'Moving out cost more than I planned, the workshop checklist helped', 'Make sure the lease says who pays what, it saved us an argument', 'Ask about the deposit refund rules before you sign', 'Our house fund pot covers surprises like a geyser repair'],
};

export const COMMUNITY_TOPIC: Record<string, keyof typeof CHAT_POOLS> = {
  wits: 'student', uj: 'student', 'pps-yp': 'payslip', 'first-salary-club': 'payslip', 'student-savers': 'student', 'invest-curious': 'invest', 'side-hustle-sisters': 'hustle',
  'stokvel-sisters': 'stokvel', 'family-and-money': 'family', 'debt-free-starters': 'debt', 'cape-town-sisters': 'general', 'rent-and-independence': 'rent',
};

export const FEED_TEMPLATES = {
  badge: (n: string, badge: string) => `${n} earned the ${badge} badge`,
  milestone: (n: string, m: string) => `${n} completed ${m}`,
  level: (n: string, l: string) => `${n} reached ${l} level`,
  weekly: (n: string, w: number) => `${n} hit their weekly target ${w} weeks running`,
};

export const NOTE_PRESETS = ['So proud of you!', 'You did it!', 'Love this 💗', 'Inspiring, thank you', 'Yes sisi!', 'Keep going!', 'This made my day', 'Teach me your ways 😄'];
export const REACTIONS = ['💗', '👏', '🔥', '🌱'] as const;
export const CHAT_EMOJI = ['👍', '💗', '🔥', '👏', '😂'] as const;
