/** Plain-language glossary. Examples are illustrative; check current rules and figures at the source (SARS, FSCA, your provider). */
export type Term = { term: string; definition: string; example: string };

export const GLOSSARY: Term[] = [
  { term: 'compound interest', definition: 'Interest earned on your money and on the interest it already earned.', example: 'Leave R1,000 growing and next year’s interest is worked out on the bigger amount, not just the R1,000.' },
  { term: 'TFSA', definition: 'A tax-free savings account: interest, dividends and growth inside it are not taxed, within SARS limits.', example: 'You put your savings in a TFSA, so the growth stays yours instead of being taxed.' },
  { term: 'unit trust', definition: 'A fund where many people pool money and a manager invests it in shares, bonds or cash. You own units of the fund.', example: 'R200 a month buys you units in a fund that holds many companies, instead of you picking one.' },
  { term: 'ETF', definition: 'An exchange-traded fund: a basket of investments that trades like a share and usually tracks an index.', example: 'One ETF can follow the biggest companies on the JSE, so you spread your money across many of them.' },
  { term: 'retirement annuity', definition: 'A retirement savings product you pay into regularly. Contributions can reduce your taxable income within limits, but the money is locked until retirement age.', example: 'You pay into an RA monthly. It may lower your tax, but you cannot dip into it for a holiday.' },
  { term: 'PAYE', definition: 'Pay-As-You-Earn: income tax your employer takes off your salary and pays to SARS for you.', example: 'Your payslip shows PAYE as a deduction, so you do not owe a lump sum later.' },
  { term: 'UIF', definition: 'Unemployment Insurance Fund: a small percentage of your pay that goes towards benefits if you lose your job or go on leave.', example: 'UIF shows as a small deduction on your payslip every month.' },
  { term: 'gross pay', definition: 'Your salary before anything is taken off.', example: 'Your offer letter says R12,000 gross. That is not what lands in your account.' },
  { term: 'net pay', definition: 'The money you actually receive after tax and other deductions.', example: 'Net pay is the number to budget with, because it is what you can really spend.' },
  { term: 'interest rate', definition: 'The percentage charged when you borrow, or paid when you save, usually shown per year.', example: 'A higher rate on a loan means you pay back more; a higher rate on savings means you earn more.' },
  { term: 'credit score', definition: 'A number that shows lenders how reliably you have repaid debt in the past.', example: 'Paying your account on time helps your score, which can mean cheaper credit later.' },
  { term: 'debit order', definition: 'A set amount taken from your bank account on an agreed date by a company you have authorised.', example: 'Your gym takes its fee on the 1st by debit order, whether you went or not.' },
  { term: 'overdraft', definition: 'Borrowing from your bank by spending more than you have in your account, usually with interest and fees.', example: 'Going R300 into overdraft means the bank lends you R300 and charges you for it.' },
  { term: 'inflation', definition: 'The rise in prices over time, which means the same rand buys less.', example: 'If prices rise, a R50 lunch today may cost more next year.' },
  { term: 'emergency fund', definition: 'Savings kept aside only for urgent, unexpected costs.', example: 'A cracked phone screen you need for study is an emergency fund moment; a sale is not.' },
  { term: 'black tax', definition: 'The financial support many people give to family members, often alongside their own costs. It is not an official tax.', example: 'Sending money home each month is a real cost, so it belongs in your budget.' },
  { term: 'monthly fee', definition: 'A fixed amount your bank charges each month to keep an account open.', example: 'A R60 monthly fee is R720 a year, even if you barely use the account.' },
  { term: 'transaction fee', definition: 'A charge each time you pay, withdraw or transfer money.', example: 'Withdrawing small amounts again and again can cost more in fees than withdrawing once.' },
  { term: 'admin fee', definition: 'A charge for managing an account, policy or investment.', example: 'An investment’s admin fee comes off your money every year, so it affects your growth.' },
  { term: 'asset', definition: 'Something you own that has value or can earn money.', example: 'Savings and investments are assets. A phone loses value, so it is not usually an investment.' },
  { term: 'liability', definition: 'Something you owe, like a loan or an unpaid account.', example: 'A store card balance is a liability until you pay it off.' },
  { term: 'diversification', definition: 'Spreading your money across different investments so one bad one hurts less.', example: 'Holding many companies in a fund is more diversified than holding just one.' },
  { term: 'risk', definition: 'The chance that an investment goes down in value or does not turn out as expected.', example: 'Shares can fall in a bad year, which is why money you need soon should not be in them.' },
  { term: 'return', definition: 'How much an investment gains or loses over a period, usually as a percentage.', example: 'A return is not guaranteed. Illustrations in Sisi are never forecasts.' },
  { term: 'bursary', definition: 'Money given to help pay for study that you usually do not pay back, often with conditions.', example: 'Your bursary may pay fees but not your rent, so budget for the rest.' },
  { term: 'NSFAS allowance', definition: 'Money from NSFAS for living costs like food, accommodation or transport while you study, depending on your funding.', example: 'Your allowance has to stretch across the whole period it is meant for.' },
  { term: 'stokvel', definition: 'A group of people who save or contribute together, often rotating payouts or saving for a shared goal.', example: 'A monthly grocery stokvel lets members buy in bulk at year-end.' },
  { term: 'budget', definition: 'A plan for what you will do with your money before you spend it.', example: 'A budget says: rent first, then food, then savings, then fun.' },
  { term: 'cash flow', definition: 'Money coming in minus money going out over a period.', example: 'Positive cash flow means money is left over at the end of the month.' },
  { term: 'fixed cost', definition: 'A cost that stays about the same every month.', example: 'Rent is a fixed cost.' },
  { term: 'flexible cost', definition: 'A cost that changes month to month and that you can influence.', example: 'Takeaways and airtime are flexible costs.' },
  { term: 'savings account', definition: 'A bank account that pays interest and is meant for money you are not spending right now.', example: 'You keep your emergency fund in a savings account you can reach within a day or two.' },
  { term: 'fixed deposit', definition: 'Money locked away for an agreed period in return for a set interest rate.', example: 'If you need the money early you may lose some interest, so only lock money you can spare.' },
  { term: 'money market', definition: 'A low-risk place to hold cash that earns interest, usually through a fund.', example: 'Some people use a money market fund for short-term savings.' },
  { term: 'dividend', definition: 'A share of a company’s profit paid out to its shareholders.', example: 'You own a tiny part of a company and it pays you a dividend.' },
  { term: 'share', definition: 'A small piece of ownership in a company.', example: 'Buying a share means you own a tiny part of that business.' },
  { term: 'bond', definition: 'A loan you give to a government or company that pays you interest and returns your money later.', example: 'A government bond is you lending to government in return for interest.' },
  { term: 'JSE', definition: 'The Johannesburg Stock Exchange, where shares in South African companies are bought and sold.', example: 'When people say the JSE is up, shares in many local companies have risen.' },
  { term: 'index', definition: 'A measure that tracks how a group of investments is doing as a whole.', example: 'An index fund copies the companies in an index instead of picking winners.' },
  { term: 'index fund', definition: 'A fund that copies an index rather than trying to beat it, which often means lower fees.', example: 'An index fund holds the same companies as the index, in the same proportions.' },
  { term: 'TER', definition: 'Total expense ratio: the yearly running cost of a fund, shown as a percentage of your investment.', example: 'A lower TER means less of your growth goes on fees.' },
  { term: 'platform fee', definition: 'A charge by the company that holds and manages your investments for you.', example: 'Two investment platforms can offer the same fund at very different total costs.' },
  { term: 'minimum contribution', definition: 'The smallest amount a provider lets you invest or save.', example: 'Some providers let you start with a small monthly amount. Compare minimums before you choose.' },
  { term: 'lump sum', definition: 'One larger payment made at once instead of small regular ones.', example: 'A bonus invested in one go is a lump sum.' },
  { term: 'debit card', definition: 'A bank card that spends money you already have in your account.', example: 'With a debit card you cannot spend more than your balance, unless you have an overdraft.' },
  { term: 'credit card', definition: 'A card that lets you spend money the bank lends you, which you must pay back, often with interest.', example: 'Paying only the minimum on a credit card means interest keeps building.' },
  { term: 'store card', definition: 'Credit from a shop that lets you buy now and pay later, often with high interest.', example: 'A 10% discount for opening a store card can cost far more in interest.' },
  { term: 'instalment', definition: 'A fixed payment you make regularly until a purchase or loan is paid off.', example: 'A phone contract is paid in monthly instalments.' },
  { term: 'loan shark', definition: 'An unregistered lender who charges extremely high interest and fees. This is illegal.', example: 'A lender who keeps your bank card as security is a major warning sign.' },
  { term: 'registered credit provider', definition: 'A lender registered with the National Credit Regulator, which must follow credit laws.', example: 'Check that a lender is registered before you sign anything.' },
  { term: 'National Credit Regulator', definition: 'The body that oversees credit providers in South Africa and protects borrowers.', example: 'You can check whether a lender is registered with the National Credit Regulator.' },
  { term: 'FSCA', definition: 'The Financial Sector Conduct Authority, which regulates financial products and providers in South Africa.', example: 'Before you invest with anyone, check they are authorised by the FSCA.' },
  { term: 'financial adviser', definition: 'A professional who gives advice on financial products and must be authorised.', example: 'A real adviser will be on the FSCA register and will explain fees in writing.' },
  { term: 'Ponzi scheme', definition: 'A scam that pays early investors with money from new investors instead of real profits.', example: 'Promises of fixed high returns with “no risk” are a classic warning sign.' },
  { term: 'phishing', definition: 'A scam message that tricks you into giving away passwords, PINs or card details.', example: 'A text saying your account is blocked, with a link to fix it, is likely phishing.' },
  { term: 'OTP', definition: 'A one-time PIN sent to confirm that it is really you doing something.', example: 'Never read your OTP out to anyone, even someone who says they are from your bank.' },
  { term: 'beneficiary', definition: 'The person or account you pay, or the person who receives money from a policy or fund.', example: 'Check the beneficiary details carefully before you send money.' },
  { term: 'premium', definition: 'The regular amount you pay for an insurance policy.', example: 'Your phone insurance premium is paid monthly whether you claim or not.' },
  { term: 'excess', definition: 'The amount you pay yourself when you make an insurance claim.', example: 'With an excess of R500 you pay the first R500 of a claim.' },
  { term: 'insurance', definition: 'A product where you pay a premium and the insurer pays out if a covered bad thing happens.', example: 'Insurance helps you cope with a big, unlikely cost like a stolen laptop.' },
  { term: 'medical aid', definition: 'A monthly plan that helps pay for private healthcare costs.', example: 'Medical aid covers certain costs, but not everything, so read what your plan includes.' },
  { term: 'life cover', definition: 'Insurance that pays money to your loved ones if you die.', example: 'People with dependants often consider life cover. Single students with none may not need it yet.' },
  { term: 'pension fund', definition: 'A workplace retirement fund that you and your employer may pay into.', example: 'Your payslip may show a pension fund contribution that builds your retirement savings.' },
  { term: 'provident fund', definition: 'A workplace retirement fund, often paying out as a lump sum at retirement.', example: 'Both you and your employer may contribute to your provident fund.' },
  { term: 'tax return', definition: 'A yearly form where you tell SARS your income and claims so your tax can be checked.', example: 'Even with PAYE, you may need to file a return and you may get a refund.' },
  { term: 'tax rebate', definition: 'An amount taken off the tax you owe.', example: 'A rebate lowers your final tax bill.' },
  { term: 'tax bracket', definition: 'A range of income taxed at a particular rate.', example: 'Only the part of your income inside a bracket is taxed at that bracket’s rate.' },
  { term: 'SARS', definition: 'The South African Revenue Service, which collects tax.', example: 'SARS publishes the current tax tables and TFSA limits.' },
  { term: 'eFiling', definition: 'SARS’s online system for filing returns and managing your tax.', example: 'You can view your tax information on eFiling after you register.' },
  { term: 'IRP5', definition: 'A tax certificate from your employer that summarises your pay and tax for the year.', example: 'You use your IRP5 details when you file your tax return.' },
  { term: 'deduction', definition: 'Something taken off your pay or off your taxable income.', example: 'Tax and UIF are deductions from your pay.' },
  { term: 'allowance', definition: 'Money you receive regularly for a purpose, such as living costs.', example: 'Your allowance has to cover food and transport until the next payment.' },
  { term: 'side hustle', definition: 'Extra work you do alongside study or a job to earn more.', example: 'Selling baked goods on campus is a side hustle. Income may be taxable.' },
  { term: 'net worth', definition: 'What you own minus what you owe.', example: 'Paying off debt and building savings both raise your net worth.' },
  { term: 'financial goal', definition: 'Something specific you want your money to do, with a time frame.', example: 'Saving for a laptop by December is a clear financial goal.' },
  { term: 'sinking fund', definition: 'Money you set aside bit by bit for a known future cost.', example: 'Saving a little each month for annual fees avoids a shock in January.' },
  { term: 'standing order', definition: 'An instruction you give your bank to send a fixed amount on a set date.', example: 'A standing order can move savings out of your account right after payday.' },
  { term: 'EFT', definition: 'An electronic funds transfer: moving money between bank accounts.', example: 'Paying rent by EFT leaves a record of the payment.' },
  { term: 'proof of payment', definition: 'A record showing that a payment was made.', example: 'Keep proof of payment for rent and big purchases.' },
  { term: 'capital', definition: 'The money you start with or put in, before it earns anything.', example: 'Your capital is the money you put into an investment, not the growth.' },
  { term: 'principal', definition: 'The original amount borrowed or invested, not counting interest.', example: 'On a loan, the principal is what you borrowed before interest is added.' },
  { term: 'maturity', definition: 'The date when a fixed investment or loan period ends.', example: 'A 12-month fixed deposit reaches maturity after a year.' },
  { term: 'liquidity', definition: 'How quickly you can turn something into cash without losing value.', example: 'Savings are liquid. A car is not.' },
  { term: 'volatility', definition: 'How much an investment’s value goes up and down.', example: 'Shares are more volatile than savings, so expect ups and downs.' },
  { term: 'time horizon', definition: 'How long you plan to keep money invested before you need it.', example: 'Money you will not need for ten years has a longer horizon than a holiday fund.' },
  { term: 'rand-cost averaging', definition: 'Investing the same amount regularly so you buy more units when prices are low and fewer when high.', example: 'A monthly R200 into a fund is rand-cost averaging.' },
  { term: 'fee drag', definition: 'The way ongoing fees quietly reduce your investment growth over time.', example: 'Over many years, a small yearly fee can cost you a large part of your growth.' },
  { term: 'cooling-off period', definition: 'A short time after signing up when you can cancel certain products without penalty.', example: 'If you regret a policy, check whether you are still inside the cooling-off period.' },
  { term: 'terms and conditions', definition: 'The rules of a contract that you agree to when you sign up.', example: 'Fees, penalties and cancellation rules are in the terms and conditions.' },
];

export const slugify = (t: string) => t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** Marks the first occurrence of each glossary term in a text with [[term]] so the player can render a tappable definition. */
export function markTerms(text: string, terms: string[]): string {
  let out = text;
  for (const t of [...terms].sort((a, b) => b.length - a.length)) {
    if (out.includes(`[[${t}]]`)) continue;
    const re = new RegExp(`(?<!\\[\\[)\\b(${t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})\\b(?![^\\[]*\\]\\])`, 'i');
    out = out.replace(re, (m) => `[[${m}]]`);
  }
  return out;
}

export const TERM_RE = /\[\[(.+?)\]\]/g;
